FROM python:3.10-slim

WORKDIR /app

# Install our dependencies
RUN pip install --no-cache-dir worldometer kafka-python

# Copy in our producer script
COPY kafka_producer.py .

CMD ["python", "kafka_producer.py"]
