FROM python:3.10-slim

# Set the working directory first
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the Kafka consumer script
COPY kafka_consumer.py .

# Run the Kafka consumer
CMD ["python", "kafka_consumer.py"]
